# BlockNotif configuration file

# Do you want a log file in BlockNotif directory?
LogFile: false

# Disables bypass permissions
Debug: true

# List here for which block you want to be notified
# You can use ['*'] for ALL blocks (Recommended only for BlockIgnite)
# For an empty list, put []
# (see https://minecraft.gamepedia.com/Java_Edition_data_values)
# Or use the "Bukkit name"
ActionListen:

    # When a user removes/takes/mines a block
    # Ignore permission: blocknotif.ignore.break.<name>[:<data>]
    BlockBreak: [DIAMOND_ORE,EMERALD_ORE, GOLD_ORE]

    # When a user places a block
    # Ignore permission: blocknotif.ignore.place.<name>[:<data>]
    BlockPlace: [TNT]
    
    # When a user puts fire
    # Ignore permission: blocknotif.ignore.ignite.<name>[:<data>]
    BlockIgnite: ['*']
    
    # When a user uses bucket
    # Be careful, cod_bucket and other buckets of fish are not counted as water bucket.
    # Ignore permission: blocknotif.ignore.bucket.<name>
    BucketUse: [WATER_BUCKET]
    
    # When a player kills an entity (villager, animal, monster, etc.)
    # Ignore permission: blocknotif.ignore.kill.<name>
    EntityKill: [VILLAGER, IRON_GOLEM, HORSE]

    # Notification when player is creative ?
    Creative: true

    # Notification when TNT explode?
    TntExplode: true
    
# Here add blocks you want to prevent
# Users will not be allowed to do those actions
ActionPrevent:
    
    # When a user removes/takes/mines a block
    # Allow permission: blocknotif.allow.break.<name>[:<data>]
    BlockBreak: []
    
    # When a user places a block
    # Allow permission: blocknotif.allow.place.<name>[:<data>]
    BlockPlace: []
    
    # When a user puts fire
    # Note: Put "49" to prevent Nether portal creation
    # Allow permission: blocknotif.allow.ignite.<name>[:<data>]
    BlockIgnite: [OBSIDIAN]
    
    # When a user uses bucket
    # Allow permission: blocknotif.allow.bucket.<name>
    BucketUse: [LAVA_BUCKET]
    
    # When a player kills an entity (villager, animal, monster, etc.)
    # Allow permission: blocknotif.allow.kill.<name>
    EntityKill: []

# You can customize colors for each items and entities
# Use "&c" format
#Color:
#    Block:
#        14: "&6"
#        21: "&1"
#        56: "&b"
#        129: "&a"
#    Entity:
#        99: "&e"
#        120: "&f"

# History keep
# Default configuration here should works for most servers
History:
    
    # Time between the first action and the notification in second (antispam)
    # In this time, next actions will be added in history
    # Lower = more chat posts, higher = more delays before notification
    TimeBeforeNotify: 30
    
    # Maximum time in second the history is keep in memory
    # Also the time between each clean up
    MaxTimeKeep: 7200
    
    # Maximum number of total entry keep in memory
    MaxEntryKeep: 300